version: "3.8"
services:
  api:
    build: ./api
    command:
      - gunicorn
      - --bind
      - api:5000
      - wsgi:app
    volumes:
      - $PWD/api:/api
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - DOMAIN=mail.nicolasarias.co
    restart: always
  postfix:
    build: postfix
    command:
      - postfix
      - start-fg
    ports:
      - "25:25"
    restart: always
    env_file: .env
    environment:
      - POSTFIX_HOSTNAME=tempmail-postfix
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/redis-data:/var/lib/redis
      - $PWD/redis/redis-data:/usr/local/etc/redis/redis.conf
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
  server:
    build: ./nginx
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    restart: always
    env_file: .env
    volumes:
      - $PWD/client/build:/usr/share/nginx/html
